Repository dapr/quickstarts, pull requests merged in 2024-02, with the labels that each got.

#976 Updating CI/CD actions to use release-1.13 of dapr/dapr runtime
  .github/env/global.env
Labels: P1

#979 Fix tests broken by timing change
  .github/env/global.env
  bindings/components/binding-cron.yaml
  bindings/components/binding-postgres.yaml
  state_management/csharp/http/README.md
  state_management/csharp/sdk/README.md
  state_management/go/http/README.md
  state_management/go/sdk/README.md
  state_management/javascript/sdk/README.md
Labels: P0

#985 Fix the DAPR bot script addressing this issue #966
  .github/workflows/dapr-bot.yml
Labels: build

#973 go-sdk workflow quickstart
  .github/workflows/validate_go_quickstarts.yaml
  pub_sub/go/http/README.md
  pub_sub/go/sdk/README.md
  secrets_management/go/http/README.md
  service_invocation/go/http/README.md
  workflows/go/sdk/README.md
  workflows/go/sdk/dapr.yaml
  workflows/go/sdk/img/workflow-trace-spans-zipkin.png
  workflows/go/sdk/makefile
  workflows/go/sdk/order-processor/go.mod
  workflows/go/sdk/order-processor/go.sum
  workflows/go/sdk/order-processor/main.go
  workflows/go/sdk/order-processor/models.go
  workflows/go/sdk/order-processor/workflow.go
Labels: P1, area/workflow, language/golang

#988 updating globals to release-1.13 RC4
  .github/env/global.env
Labels: P0

#990 Updating to RC6 which has fix to #982
  .github/env/global.env
  bindings/components/binding-cron.yaml
  bindings/components/binding-postgres.yaml
Labels: P0, area/bindings

#975 correct readme
  workflows/python/sdk/README.md
Labels: area/workflow

#989 Add workflow quickstart for JS
  .gitignore
  actors/csharp/sdk/service/SmokeDetectorActor.cs
  service_invocation/csharp/http/checkout/Program.cs
  service_invocation/csharp/http/checkout/checkout.csproj
  state_management/csharp/http/README.md
  state_management/csharp/sdk/README.md
  state_management/go/http/README.md
  state_management/go/sdk/README.md
  state_management/javascript/sdk/README.md
  workflows/csharp/sdk/order-processor/Program.cs
  workflows/javascript/sdk/README.md
  workflows/javascript/sdk/dapr.yaml
  workflows/javascript/sdk/makefile
  workflows/javascript/sdk/order-processor/model.ts
  workflows/javascript/sdk/order-processor/orderProcessingWorkflow.ts
  workflows/javascript/sdk/order-processor/workflowApp.ts
  workflows/javascript/sdk/package-lock.json
  workflows/javascript/sdk/package.json
  workflows/javascript/sdk/tsconfig.json
Labels: P1, language/javascript, area/workflow

#994 Test fix: Removing `toolchain go*` lines that cause midstream downloads
  state_management/go/sdk/order-processor/go.mod
  workflows/go/sdk/order-processor/go.mod
Labels: P1
